### PR TITLE
Added the 2d task

### PR DESCRIPTION
**Pull request by lllerony**

### CODE REVIEW

**Review by Dann-Go — CHANGES_REQUESTED** [review]
Did you write any benchmarks as requested in the task?

**Comment by lllerony** [comment]
> Did you write any benchmarks as requested in the task?

I did. But In which format should I write it?

**Review by Dann-Go — APPROVED** [review]
LGTM

**Comment by lllerony** [comment]
> LGTM

Good. That means that I can merge?)

**Comment by Dann-Go** [comment]
> > LGTM
> 
> Good. That means that I can merge?)

yes

**Pull request merged**
